### ISSUE TITLE
Blank Screen / Possibly Won't Open .textgrid

### ISSUE THREAD

**Issue by Steve-Miller** [langtech/toney#11]
I downloaded Toney and ran it. Screen shot of the opening screen: ![toney-blank](https://cloud.githubusercontent.com/assets/583475/7174357/d67a7110-e449-11e4-9c3d-551585d1608e.jpg)

I did File > Open and selected a .textgrid file, created by annotating a .wav in Praat. Toney is still blank. 

I did File > Open Directory, selected the directory where the .wav and the .textgrid files live. Toney is still blank. 

I copied the .wav and .textgrid files to the Toney directory and tried to open them. Toney is still blank.

I set up the .textgrid file with four tiers, as was found in an article: target, frame, speaker, and comments. Screen shot of the .textgrid in Praat: 
![praat-with-target-tier](https://cloud.githubusercontent.com/assets/583475/7174445/841df3c2-e44b-11e4-802c-ba3a15f26041.jpg)

This looks like a helpful tool. I hope this doesn't take too much effort to fix.

**Comment by Steve-Miller** [comment]
Apparently this app relies on the QT library. The QT .dlls I see were compiled three years ago. Since I have a 64 bit machine, I at once became suspicious of these. I went to the readme.txt (imagine that) and discovered the note about .dlls there. I ran vcredist_x86.exe, which turned up an error: 

"A newer version of Microsoft Visual C++ 2010 Redistributable has been detected on the machine."

After some trial and error and such, I discovered that vcredist_x86.exe _is_ the MS Visual C++ 2010 Redistributable. There are at least half a dozen of these on my machine already for other apps, and a vcredist_x64.exe, too. I could well believe a newer version exists on this machine.

I know the source code exists here on github, and I'd like to compile a version for my machine. But it's been some years since I had Visual Studio on my computer, and even then I never quite understood C++ and its compilation. I think I'm as far as I can go resolving this issue.

**Comment by hleeldc** [comment]
Hi-- Regarding your first comment, I would make sure that your TextGrid file is in the right format. Praat has the long format and the short format. Toney uses the long format. Please check that.

As long as you don't get any error message about missing VC++ runtime dlls, the VC++ redistributable doesn't have to be installed. It looks like the tool opens file for you. So, I wouldn't worry about your second comment.

**Comment by Steve-Miller** [comment]
Hello. Thanks for the reply. Responses are inline below.

On 4/21/2015 0:31, hleeldc wrote:

> Hi-- Regarding your first comment, I would make sure that your 
> TextGrid file is in the right format. Praat has the long format and 
> the short format. Toney uses the long format. Please check that.

Okay. How do I check if the textgrid file is in long format or short 
format? I don't see any help online.

I created the file in Praat by:
1. Open > Open long sound file...
2. selecting a .wav file.
3. Clicking the Annotate button, then selecting To TextGrid...
4. I listed the tier names I wanted in the LongSound: To Textgrid...
   window and pressed OK. This resulted in a second file open in the
   Praat Objects window.

The header of the file and the first intervals array are as follows. 
(I'm not sure indents will stay once I post this):

File type = "ooTextFile"
Object class = "TextGrid"

xmin = 0
xmax = 666.7049886621315
tiers? <exists>
size = 4
item []:
     item [1]:
         class = "IntervalTier"
         name = "target,"
         xmin = 0
         xmax = 666.7049886621315
         intervals: size = 274
         intervals [1]:
             xmin = 0
             xmax = 0.8079294733153275
             text = ""

> As long as you don't get any error message about missing VC++ runtime 
> dlls, the VC++ redistributable doesn't have to be installed. It looks 
> like the tool opens file for you. So, I wouldn't worry about your 
> second comment.

I agree that Toney.exe appears to run. It may indeed open the .textgrid 
file, but I'd feel better with a little more proof.

Thanks again for looking at this.

Steve

**Comment by Steve-Miller** [comment]
(For some reason, the second half of my message appears as a quoted comment that you have to click on to see. I've tried to fix it, but it doesn't want to fix.)

Okay, I tried again. I did all the steps that I listed in the previous 
comment and made three test annotations. Then:
1. I went to the Praat Objects window
2. Selected just the word list from the Objects list
3. Selected Save from the menu.
4. Selected Save as text file... and saved the file.
5. I opened the saved file in Toney.

The three test annotations appear on the canvas--hurray!--but they don't work. I can drag them around on the canvas, but I hear nothing when I click on them. I've dragged the Amplitude slider all the way up to 25, and turned up the sound on my computer, but still I hear nothing.

I have a lot of time invested in the transcriptions in my first textgrid file. I tried saving this with the same steps as above, but I still do not see any words appear on the canvas.

Steve

**Comment by hleeldc** [comment]
I'm glad that your test annotations showed up in the tool. I'm not sure why your original file didn't display though. What you posted in the earlier comment is the long format.

You have to double click on the items on the canvas to listen to them. Also, they have a right click menu. (I noticed a bug where the "Melody" menu doesn't work until the item is added to a cluster.)

**Comment by Steve-Miller** [comment]
This thread is drifting. I'll open up a new bug report.

**Comment by Steve-Miller** [comment]
Okay, I figured out the problem by comparing the test file I made yesterday side-by-side with my first file. If you look at the file header I posted yesterday, a couple of comments up, you can see it:

```
     name = "target,"
```

There's a comma in the tier name. I removed that comma, and the comma from two other tier names, and saved the file. I opened the file with Toney and suddenly had 100+ words on the canvas.

When I had initially set up the .textgrid file in Praat, I used a comma-delimited list in the Tier names field: target, frame, speaker, comments. I should have instead entered: "target frame speaker comments.

If you ever do another version of Toney, stripping out commas in the tier name would be a nice enhancement.

**Comment by hleeldc** [comment]
I didn't notice the comma. That was the culprit.
